before:
  hooks:
    - go mod download
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    binary: lazycomplete
    tags:
      - release
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    name_template: "lazycomplete_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
brews:
  -
    name: lazycomplete
    description: "lazy loading for shell completion scripts"
    homepage: "https://github.com/rsteube/lazycomplete"
    license: "MIT"
    tap:
      owner: rsteube
      name: homebrew-tap
      token: "{{ .Env.GORELEASER_GITHUB_TOKEN }}"
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
scoop:
  description: "lazy loading for shell completion scripts"
  homepage: "https://github.com/rsteube/lazycomplete"
  license: "MIT"
  bucket:
    owner: rsteube
    name: scoop-bucket
    token: "{{ .Env.GORELEASER_GITHUB_TOKEN }}"
  commit_msg_template: "Scoop update for {{ .ProjectName }} version {{ .Tag }}"
aurs:
  -
    description: "lazy loading for shell completion scripts"
    homepage: "https://github.com/rsteube/lazycomplete"
    license: "MIT"
    maintainers:
      - rsteube <rsteube@users.noreply.github.com>
    private_key: '{{ .Env.AUR_KEY }}'
    git_url: 'ssh://aur@aur.archlinux.org/lazycomplete-bin.git'

nfpms:
  -
    description: "lazy loading for shell completion scripts"
    homepage: "https://github.com/rsteube/lazycomplete"
    license: "MIT"
    maintainer: rsteube <rsteube@users.noreply.github.com>
    formats:
      - apk
      - deb
      - rpm
